[build]
  publish = "."
  functions = "api"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, x-user-api-key"
    Access-Control-Allow-Methods = "POST, OPTIONS"
